pipeline {

    environment {

      ANSIBLE_VAULT_PASSWORD_FILE = "./vault.txt"

    }


    agent { label 'cdnode' }  
    
    stages {

      stage('Jenkins: Determine Operations'){
        steps {
          script {
                   def operation = "deploy"  
                 }
                }
              }

     stage('Ansible: Decrypt Files') {
	agent {	docker 'ansible/ansible' }	
         steps{
           withCredentials([string(credentialsId: 'AnsibleVault', variable: 'PASS')]) {
              sh """
                    echo $PASS > ./vault.txt

                    ansible-vault decrypt --vault-password-file="${ANSIBLE_VAULT_PASSWORD_FILE}" "./env/init_protocol.tfvars"
                    ansible-vault decrypt --vault-password-file="${ANSIBLE_VAULT_PASSWORD_FILE}" "./env/plan_protocol.tfvars"

              """
                  }
                }
              }

      stage('Terraform: Init') {
        agent { docker 'hashicorp/terraform' }
          steps {
             sh '''
                   terraform init --backend-config=init.tfvars
             '''
            }
        }
        
      stage('Terraform: Plan') {
        agent { docker 'hashicorp/terraform' }      
  	steps {
                sh '''
                terraform plan -var-file=plan.tfvars -out=${BUILD_NUMBER}.tfplan
                '''
            }
        }
        
        stage('Terraform: Apply') {
            agent { docker 'hashicorp/terraform' }
		steps {
                sh '''
                terraform init ${BUILD_NUMBER}.tfplan --auto-approve
                '''
            }
        }
        stage('Terraform: Destroy') {
            agent { docker 'hashicorp/terraform' }
		steps {
                sh '''
                terraform destroy -var-file=init.tfvars -var-file=plan.tfvars --auto-approve
                '''
            }
        }
        
    }
            post {
                always {
                  step([$class: 'WsCleanup'])
                }
            }
}
